version: '2'
services:
  web:
    build: .
    # volumes:
    #   - .:/var/www/html
    depends_on:
      - db
    ports:
      - 8001:80

  db:
    image: mysql:5.7
    ports:
      - 33306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contacts
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
